### ISSUE TITLE
Parse error from GLSL Geometry shader

### ISSUE THREAD

**Issue by wrightwriter** [laurentlb/shader-minifier#29]
Related: GLSL Compute shader throws same error https://github.com/laurentlb/Shader_Minifier/issues/22

Passthrough compute shade:

```glsl
#version 330

layout(triangles) in;
layout(triangle_strip, max_vertices = 3) out;

void main() {
  for(int i = 0; i < 3; i++) { 
    gl_Position = gl_in[i].gl_Position;
    EmitVertex();
  }
  EndPrimitive();
}
```

results in:

> Parse error: Error in triGeometry_g.geom: Ln: 3 Col: 21
> layout(triangles) in;
>                     ^
> Expecting: Type qualifier, identifier, 'layout' or 'struct'

**Comment by laurentlb** [comment]
Workaround: add verbatim markers.

```glsl
//[
layout(triangles) in;
layout(triangle_strip, max_vertices = 3) out;
//]
```
