### ISSUE TITLE
Redefinition error not enforced

### ISSUE THREAD

**Issue by therontarigo** [laurentlb/shader-minifier#437]
Invalid Input
```GLSL
#version 450
out vec4 out_color;
void main () {
  float a = .1, b = .2, c = .3;
  float c = .4, b = .5;
  out_color = vec4(a, b, c, 1);
}
```
There is output when there should be an error:
```GLSL
#version 450
out vec4 out_color;
void main()
{
  out_color=vec4(.1,.5,.4,1);
}
```

With `--no-inlining --no-remove-unused`, there is broken output when there should be an error:
```GLSL
#version 450
out vec4 out_color;
void main()
{
  float a=.1,b=.2,c=.3,c=.4,b=.5;
  out_color=vec4(a,b,c,1);
}
```

**Comment by eldritchconundrum** [comment]
Shader Minifier emits errors when it cannot minify, but it intentionally doesn't verify that the shader is valid.
It assumes that the shader is valid.
This is so that it can just ignore the glsl/hlsl features that it does not understand, but still manage to minify them correctly sometimes.

**Comment by therontarigo** [comment]
Indeed, and I have known this "bug" before and only bothered to report it this time to document it, since it appeared to confound a real bug, #436.
Closing as "won't fix".
